;;; build-site.el --- Website Build Script Emacs Lisp  -*- lexical-binding: t; -*-

;; This file was auto-generated by website.org

;; Copyright (C) 2022 Erik P. Almaraz
;; License: MIT

;;; Code:

;; Load the publishing system
(require 'ox-publish)

;; Define the publishing project
(setq org-publish-project-alist
      (list
       (list "almarazlabs-org-site"
             :recursive t
             :base-directory "./content"
             :publishing-directory "./public"
             :publishing-function 'org-html-publish-to-html)))

;; Generate the site output
(org-publish-all t)

(message "Build complete!")
