;;; build-site.el --- Website Build Script Emacs Lisp  -*- lexical-binding: t; -*-

;; This file was auto-generated by website.org

;; Copyright (C) 2022 Erik P. Almaraz
;; License: MIT

;;; Code:

;; Set the package installation directory so that packages aren't stored in the
;; ~/.emacs.d/elpa path.
(require 'package)
(setq package-user-dir (expand-file-name "./.packages"))
(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))

;; Initialize the package system
(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))

;; Install dependencies
(package-install 'htmlize)

;; Load the publishing system
(require 'ox-publish)

;; Customize the HTML output
(setq org-html-validation-link t               ;; Don't not show validation link
      org-html-head-include-scripts nil        ;; Use our own scripts
      org-html-head-include-default-style nil) ;; Use our own styles

(setq org-html-head (concat "<link rel=\"stylesheet\" "
                            "href=\"https://cdn.simplecss.org/simple.min.css\"/>"))

;; Define the publishing project
(setq org-publish-project-alist
      '(("org-website"
         :base-directory "./content"
         :base-extension "org"
         :publishing-directory "./docs"
         :recursive t
         :exclude "org-html-themes/.*"
         :publishing-function 'org-html-publish-to-html
         :headline-levels 4
         :with-aurthor t
         :with-creator t
         :with-toc t
         :section-numbers nil
         :time-stamp-file t
         :auto-preamble t)))


(org-publish-all t)
(message "Build complete!")


;;; end build-site.el
