#+TITLE: Λ L M A R A Z  •  L Λ B S
#+SUBTITLE: My Personal Website
#+STARTUP: show2levels
#+SETUPFILE: ~/.config/org-files/Templates/latex-export.org


* Introduction

I originally built this website with the idea of creating my own web application framework for gaming using TypeScript, Gulp.js, webpack and Babylon.js. However, life happened and well this framework was difficult to maintain and was minimal at best. And due to my neglect over the past two years, it became so outdated that getting it working again was more work than developing a new system.

Then, after my adventures of deep-diving into all things Emacs related and presented with the /necessity/ to update my much outdated website, this led me to do so using Emacs' infamous Org Mode.

This work is still in the very early stages of development, so there are many things to figure out - such as the exact type of site I want to build.


* Outline of Features to Implement

This will act as a log of changes and a way to keep track of development. I will eventually turn this into a true README once this website is complete - for now it is a work in progress (WIP).

- DONE +Change README into Org file+
- DONE +Research Emacs/Org Manuals on  Exporting to HTML, and the [[https://systemcrafters.net/publishing-websites-with-org-mode/building-the-site/][web]]!+
- DONE +Set up Org Publishing Configuration+
- DONE +Create Build Script (Shell & Emacs Lisp) to build out pages/website automatically+
- TODO Optimize generated HTML Output
- TODO Setup CSS build/exports (babel?)
- TODO Setup GitHub Actions for automatic build upon commit (use build script)
- TODO Investigate more Advanced Org Website capabilities
- TODO Begin content curation & creation


* License

This website and its code is licensed under MIT, until further noticed - I may choose to license under Unlicense (https://unlicense.org/).


* References
:PROPERTIES:
:UNNUMBERED: nil
:END:

 1. Wilson, D., *Build Your Website with Org Mod*, /System Crafters/, 2021, [[https://systemcrafters.net/publishing-websites-with-org-mode/building-the-site/][Link]] .
 2. Wilson, D., *Automated Org Mode Website Publishing...*, /System Crafters/, 2021, [[https://systemcrafters.net/publishing-websites-with-org-mode/automated-site-publishing/][Link]] .
 3. Quirk, K., *Simple.css - A classless CSS framework*, /Simple.css/, 2022, [[https://simplecss.org/][Link]] .
 4. Org Community .
 5. Emacs Community .
